name: Docker Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_REPO: deercloud
  IMAGE_NAME: shadowsocks

jobs:
  build-cross:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
      packages: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and release Docker images
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:dev-rust
          push: true